### ISSUE TITLE
Publish to Github registry

### ISSUE THREAD

**Issue by metrue** [honojs/graphql-server#10]
https://github.com/honojs/graphql-server/packages

**Comment by yusukebe** [comment]
Hi, don't you make the release tag on GitHub? Like this:
https://github.com/honojs/hono/releases

**Comment by metrue** [comment]
@yusukebe 
just enable the auto release tagging with https://github.com/honojs/graphql-server/pull/17

**Comment by yusukebe** [comment]
I'll close this issue. Continue in the monorepo.
