### ISSUE TITLE
how to show graphiql ?

### ISSUE THREAD

**Issue by francelwebdev** [honojs/graphql-server#19]
how to show graphiql ?

**Comment by yusukebe** [comment]
Hi @francelwebdev !

Now, this middleware does not support "graphiql". Do you want it?

@metrue 
Do you have a plan to implement it? It's not difficult. We have to just refer to [express-graphql](https://github.com/graphql/express-graphql).

**Comment by metrue** [comment]
@yusukebe  Yes, I plan to enable support it by options, might be able to deliver it in next week.

Hi, @francelwebdev if you hope to open PR to implement it, super welcome 😄

**Comment by yusukebe** [comment]
This repository will be archived. Let's continue the discussion here.

https://github.com/honojs/middleware/issues/38
