### ISSUE TITLE
Type difference with hono 2.6.1

### ISSUE THREAD

**Issue by sirganya** [honojs/graphql-server#20]
Hi there,

The context type in Hono seems to have changed 

[new type](https://github.com/honojs/hono/blob/e6635e9997dca10013d1bcab53043b6fb2f936f7/src/context.ts#L17 )

and it breaks the typing in graphql-server.

**Comment by yusukebe** [comment]
Hi @sirganya !

This issue may be fixed with #21 . It has been released now as v0.1.1. Could you check it out?
